Repository Azure/azure-sdk-for-ios, pull requests merged in 2020-11, with the labels that each got.

#543 Sync eng/common directory with azure-sdk-tools for PR 1160
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#545 Sync eng/common directory with azure-sdk-tools for PR 1167
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#546 Sync eng/common directory with azure-sdk-tools for PR 1175
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#550 Sync eng/common directory with azure-sdk-tools for PR 1163
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#551 Sync eng/common directory with azure-sdk-tools for PR 1178
  eng/common/README.md
Labels: Central-EngSys, EngSys

#552 Sync eng/common directory with azure-sdk-tools for PR 1185
  eng/common/README.md
Labels: Central-EngSys, EngSys

#554 Sync eng/common directory with azure-sdk-tools for PR 1188
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#555 Sync eng/common directory with azure-sdk-tools for PR 1190
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#548 Sync eng/common directory with azure-sdk-tools for PR 1170
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#544 Sync eng/common directory with azure-sdk-tools for PR 1161
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#556 Sync eng/common directory with azure-sdk-tools for PR 1199
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#557 Sync eng/common directory with azure-sdk-tools for PR 1202
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#553 Add more PR labels.
  .github/CODEOWNERS
Labels: Central-EngSys, EngSys

#558 Sync eng/common directory with azure-sdk-tools for PR 1153
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#559 Sync eng/common directory with azure-sdk-tools for PR 1210
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#562 Revert "Updates to Support Autorest.Swift. (#522)"
  sdk/communication/AzureCommunicationChat/Source/AzureCommunicationChatClient.swift
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/Source/DataStructures/AzureDate.swift
  sdk/core/AzureCore/Source/Errors.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineClient.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/AddDatePolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/HTTPHeader.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/HTTPRequest.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/RequestParameters.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/URLHTTPResponse.swift
  sdk/core/AzureCore/Source/Util/AzureCodable.swift
  sdk/core/AzureCore/Source/Util/ConvertingInitializers.swift
  sdk/core/AzureCore/Source/Util/RequestString.swift
  sdk/core/AzureCore/Source/Util/URLUtil.swift
  sdk/core/AzureCore/Tests/AddDatePolicyTests.swift
  sdk/core/AzureCore/Tests/AzureDateTests.swift
  sdk/core/AzureCore/Tests/CollectionsTests.swift
  sdk/core/AzureCore/Tests/HTTPRequestTests.swift
  sdk/core/AzureCore/Tests/HeadersValidationPolicyTests.swift
  sdk/core/AzureCore/Tests/LoggingPolicyTests.swift
  sdk/core/AzureCore/Tests/PipelineRequestTests.swift
  sdk/core/AzureCore/Tests/PipelineTests.swift
  sdk/core/AzureCore/Tests/RequestParametersTests.swift
  sdk/core/AzureCore/Tests/Stubs/HTTPHeaderStub.swift
  sdk/core/AzureCore/Tests/Stubs/TestClient.swift
  sdk/core/AzureCore/Tests/UtilTests.swift
  sdk/core/AzureCore/Tests/XMLModelTests.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASCredential.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASToken.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSharedKeyCredential.swift
  sdk/storage/AzureStorageBlob/Source/Models/BlobProperties.swift
  sdk/storage/AzureStorageBlob/Source/Models/Enumerations.swift
  sdk/storage/AzureStorageBlob/Source/Options/ClientMethodOptions.swift
  sdk/storage/AzureStorageBlob/Source/Options/OptionsModels.swift
  sdk/storage/AzureStorageBlob/Source/StorageBlobClient+Extensions.swift
  sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
  sdk/storage/AzureStorageBlob/Source/Transport/StorageHTTPHeader.swift
  sdk/storage/AzureStorageBlob/Source/Util/StorageBlobClient+AllowLoggingValues.swift
  sdk/storage/AzureStorageBlob/Source/Util/StorageJSONCoding.swift
  sdk/storage/AzureStorageBlob/Tests/StorageSharedKeyAuthenticationPolicyTests.swift
Labels: Azure.Core, Communication, Storage

#563 Regenerate AzureCommunicationChat
  AzureSDK.xcworkspace/contents.xcworkspacedata
  CHANGELOG.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/Source/AzureCommunicationChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/AzureCommunicationChatService.swift
  sdk/communication/AzureCommunicationChat/Source/Custom/AzureCommuncationChatClient+Convenience.swift
  sdk/communication/AzureCommunicationChat/Source/Models/AddChatThreadMembersRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadInfo.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadMember.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadMembersCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadsInfoCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Models/CreateChatThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ErrorType.swift
  sdk/communication/AzureCommunicationChat/Source/Models/IndividualStatusResponse.swift
  sdk/communication/AzureCommunicationChat/Source/Models/MultiStatusResponse.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Models/SendChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/SendChatMessageResult.swift
  sdk/communication/AzureCommunicationChat/Source/Models/SendReadReceiptRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/UpdateChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/UpdateChatThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AddChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+AddChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+GetChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+ListChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+RemoveChatThreadMemberOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatService+UpdateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/GetChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/ListChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/RemoveChatThreadMemberOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Options/UpdateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Util/Primitives+Extension.swift
Labels: Communication

#560 Prepare SDK for beta.5 release
  AzureCommunication.podspec
  AzureCommunicationCalling.podspec
  AzureCommunicationChat.podspec
  AzureCore.podspec
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#565 Sync eng/common directory with azure-sdk-tools for PR 1203
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#566 Sync eng/common directory with azure-sdk-tools for PR 1222
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#567 Sync eng/common directory with azure-sdk-tools for PR 1219
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/assets/logo.svg
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/partials/affix.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/enum.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/namespace.tmpl.partial
  eng/common/docgeneration/templates/matthews/styles/main.css
  eng/common/docgeneration/templates/matthews/styles/main.js
  eng/common/pipelines/templates/steps/docindex.yml
Labels: Central-EngSys, EngSys

#575 Prepare beta.6 release
  AzureCommunication.podspec
  AzureCommunicationCalling.podspec
  AzureCommunicationChat.podspec
  AzureCore.podspec
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunication/Tests/ObjCCommunciationUserCredentialTests.m
  sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#569 Sync eng/common directory with azure-sdk-tools for PR 1226
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/docindex.yml
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#577 Sync eng/common directory with azure-sdk-tools for PR 1229
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#564 Switch to *.podspec.json format for better automation.
  AzureCommunication.podspec
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec
  AzureCommunicationChat.podspec.json
  AzureCore.podspec
  AzureCore.podspec.json
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/steps/verify-versions.yml
  eng/scripts/Verify-Versions.ps1
Labels: Central-EngSys, EngSys

#568 Sync eng/common directory with azure-sdk-tools for PR 1220
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys
