Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-05, with the labels that each got.

#842 Sync eng/common directory with azure-sdk-tools for PR 1579
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#845 Sync eng/common directory with azure-sdk-tools for PR 1524
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#846 Changelog and podspec update for 1.0.1 release of AzureCommunicationCalling
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#847 Make internal model & generated func to internal access level
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Custom.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/AzureCommunicationChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+GetChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThread+UpdateChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/IdentifierSerializerTests.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/JwtTokenParser.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
Labels: Azure.Core, Communication

#848 Sync eng/common directory with azure-sdk-tools for PR 1596
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#849 Re-enable Check Version script on CI
  eng/ignore-links.txt
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/version.py
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/Package.swift
Labels: Communication

#852 Sync eng/common directory with azure-sdk-tools for PR 1597
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#853 Sync eng/common directory with azure-sdk-tools for PR 1594
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#855 Stubbing our release stages
  eng/pipelines/templates/stages/archetype-ios-release.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  sdk/communication/ci.yml
  sdk/core/ci.yml
  sdk/identity/ci.yml
  sdk/storage/ci.yml
Labels: Azure.Core, Central-EngSys, Communication, EngSys, Storage

#858 Sync eng/common directory with azure-sdk-tools for PR 1598
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#859 Sync eng/common directory with azure-sdk-tools for PR 1585
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#860 Sync eng/common directory with azure-sdk-tools for PR 1615
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: Central-EngSys, EngSys

#861 Add template ci.yml.
  sdk/template/ci.yml
Labels: Central-EngSys, EngSys

#856 Update Chat Visibility
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatClientInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContentInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadPropertiesInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadRequestInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadResultInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatThreadPropertiesOptions.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
Labels: Communication

#862 Add tagging on release
  eng/pipelines/templates/stages/archetype-ios-release.yml
  eng/scripts/Language-Settings.ps1
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/AzureTemplate/CHANGELOG.md
Labels: Central-EngSys, EngSys

#865 Sync eng/common directory with azure-sdk-tools for PR 1627
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#863 Update Chat Visibility
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatClientInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContentInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadPropertiesInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadRequestInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadResultInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatThreadPropertiesOptions.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
Labels: Azure.Core, Communication

#866 Chat - Update dependencies
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/Package.swift
Labels: Communication

#867 Sync eng/common directory with azure-sdk-tools for PR 1629
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#870 Sync eng/common directory with azure-sdk-tools for PR 1635
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#864 CocoaPods push support
  eng/pipelines/templates/stages/archetype-ios-release.yml
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/AzureTemplate/CHANGELOG.md
Labels: Central-EngSys, EngSys

#871 Sync eng/common directory with azure-sdk-tools for PR 1606
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-environments.yml
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
Labels: Central-EngSys, EngSys
