Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-04, with the labels that each got.

#795 Sync eng/common directory with azure-sdk-tools for PR 1525
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/Update-TestResources.cmd
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#765 Signaling support for Chat Preview 5
  AzureCommunicationChat.podspec.json
  CHANGELOG.md
  Package.swift
  Podfile
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterSettings.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/events/chat.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/createThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/getThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listMessages.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listReadReceipts.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listThreads.json
Labels: Communication

#798 Release 1.0.0 beta.10
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec.json
  AzureCore.podspec.json
  AzureSDK.xcworkspace/contents.xcworkspacedata
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj
  jazzy/AzureCommunication.yml
  jazzy/AzureCommunicationChat.yml
  jazzy/AzureCore.yml
  jazzy/AzureIdentity.yml
  jazzy/AzureStorageBlob.yml
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#797 Sync eng/common directory with azure-sdk-tools for PR 1535
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#800 Prep release 1.0.0-beta.11
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec.json
  AzureCore.podspec.json
  AzureSDK.xcworkspace/contents.xcworkspacedata
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCommunication.yml
  jazzy/AzureCommunicationChat.yml
  jazzy/AzureCore.yml
  jazzy/AzureIdentity.yml
  jazzy/AzureStorageBlob.yml
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#802 Update chat README
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#805 Sync eng/common directory with azure-sdk-tools for PR 1546
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#806 Sync eng/common directory with azure-sdk-tools for PR 1548
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#804 Sync eng/common directory with azure-sdk-tools for PR 1515
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: Central-EngSys, EngSys

#807 Sync eng/common directory with azure-sdk-tools for PR 1534
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#808 Sync eng/common directory with azure-sdk-tools for PR 1551
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#809 Sync eng/common directory with azure-sdk-tools for PR 1504
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#810 Sync eng/common directory with azure-sdk-tools for PR 1553
  eng/common/pipelines/templates/steps/retain-run.yml
Labels: Central-EngSys, EngSys

#812 Sync eng/common directory with azure-sdk-tools for PR 1552
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#816 Sync eng/common directory with azure-sdk-tools for PR 1557
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys

#817 Sync eng/common directory with azure-sdk-tools for PR 1555
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#819 Sync eng/common directory with azure-sdk-tools for PR 1559
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#822 Sync eng/common directory with azure-sdk-tools for PR 1563
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, EngSys

#825 Remove unused CommunicationCache class
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
Labels: Communication

#824 Sync eng/common directory with azure-sdk-tools for PR 1564
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#826 Sync eng/common directory with azure-sdk-tools for PR 1558
  eng/common/pipelines/templates/steps/set-default-branch.yml
Labels: Central-EngSys, EngSys

#823 Sync eng/common directory with azure-sdk-tools for PR 1565
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
Labels: Central-EngSys, EngSys

#789 Mechanism for Mono to Clone Swift PM Repos
  AzureSDK.xcworkspace/contents.xcworkspacedata
  CHANGELOG.md
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/podlint.sh
  eng/scripts/sync_repo.py
  eng/scripts/util.py
  eng/scripts/version.py
  examples/AzureSDKSmokeTest/Podfile
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/Assets.xcassets/AccentColor.colorset/Contents.json
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/Assets.xcassets/AppIcon.appiconset/Contents.json
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/Assets.xcassets/Contents.json
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPMApp.swift
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/ContentView.swift
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/Info.plist
  examples/AzureSDKSmokeTestSwiftPM/AzureSDKSmokeTestSwiftPM/Preview Content/Preview Assets.xcassets/Contents.json
  sdk/communication/AzureCommunication/AzureCommunication.podspec.json
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/CHANGELOG.md
  sdk/communication/AzureCommunication/Package.swift
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
  sdk/communication/AzureCommunicationCalling/Package.swift
  sdk/communication/AzureCommunicationCalling/README.md
  sdk/communication/AzureCommunicationCalling/Source/Supporting Files/Info.plist
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Swagger/CONFIG.md
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/Package.swift
  sdk/core/AzureCore/README.md
Labels: Azure.Core

#835 Release AzureCore 1.0.0 beta.12
  eng/ignore-links.txt
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCore.yml
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/CHANGELOG.md
Labels: Azure.Core

#832 Sync eng/common directory with azure-sdk-tools for PR 1562
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#829 Release AzureCommunicationCommon 1.0.0. Deprecate AzureCommunication.
  AzureSDK.xcworkspace/contents.xcworkspacedata
  AzureSDK.xcworkspace/xcshareddata/xcschemes/all.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/communication.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/sdk.xcscheme
  Podfile
  README.md
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCommunicationCommon.yml
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessageReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatParticipant.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadProperties.swift
  sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/events/chat.swift
  sdk/communication/AzureCommunicationChat/Source/Token/TokenCredentialAdapter.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/IdentifierSerializerTests.swift
  sdk/communication/AzureCommunicationCommon/AzureCommunication.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/xcshareddata/xcschemes/AzureCommunicationCommon.xcscheme
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/Package.swift
  sdk/communication/AzureCommunicationCommon/README.md
  sdk/communication/AzureCommunicationCommon/Source/Authentication/AutoRefreshTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationAccessToken.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredentialProviding.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenRefreshOptions.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/JwtTokenParser.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/StaticTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
  sdk/communication/AzureCommunicationCommon/Source/CommunicationCloudEnvironment.swift
  sdk/communication/AzureCommunicationCommon/Source/Identifiers.swift
  sdk/communication/AzureCommunicationCommon/Source/Supporting Files/Info.plist
  sdk/communication/AzureCommunicationCommon/Tests/AzureCommunicationCommonTests-Bridging-Header.h
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierTest.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/Info.plist
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCTokenParserTests.m
Labels: Communication

#837 CommunicationCommon Updates
  sdk/communication/AzureCommunicationCommon/AzureCommunication.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/README.md
Labels: Communication

#838 Changelog for first GA Calling release v1.0.0
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#836 Update Calling README.md
  sdk/communication/AzureCommunicationCalling/README.md
Labels: Communication

#839 Release AzureCommunicationCalling 1.0.0
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
Labels: Communication

#840 Sync eng/common directory with azure-sdk-tools for PR 1580
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#843 Sync eng/common directory with azure-sdk-tools for PR 1572
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#841 Sync eng/common directory with azure-sdk-tools for PR 1577
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#844 Sync eng/common directory with azure-sdk-tools for PR 1584
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys
