Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-12, with the labels that each got.

#1088 Sync eng/common directory with azure-sdk-tools for PR 2248
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: EngSys, Central-EngSys

#1098 Sync eng/common directory with azure-sdk-tools for PR 2352
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#1099 Sync eng/common directory with azure-sdk-tools for PR 2372
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1100 Sync eng/common directory with azure-sdk-tools for PR 2380
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#1101 Azure Communication Calling release 2.2.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1102 Sync eng/common directory with azure-sdk-tools for PR 2327
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1104 Sync eng/common directory with azure-sdk-tools for PR 2381
  eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
  eng/common/scripts/Write-FileSystemMetrics.ps1
Labels: EngSys, Central-EngSys

#1103 Sync eng/common directory with azure-sdk-tools for PR 2363
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1105 Sync eng/common directory with azure-sdk-tools for PR 2393
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1106 Sync eng/common directory with azure-sdk-tools for PR 2402
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#1107 Sync eng/common directory with azure-sdk-tools for PR 2408
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1108 Sync eng/common directory with azure-sdk-tools for PR 2412
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, auto-merge, Central-EngSys

#1110 Sync eng/common directory with azure-sdk-tools for PR 2415
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1111 Sync eng/common directory with azure-sdk-tools for PR 2417
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#1112 Azure Communication Calling v2.0.0 release
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1113 Sync eng/common directory with azure-sdk-tools for PR 2442
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#1116 Sync eng/common directory with azure-sdk-tools for PR 2447
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
