Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-08, with the labels that each got.

#982 Remove recording destination hard coding
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme
  sdk/test/AzureTest/Source/DVRSessionTransport.swift
Labels: Communication

#980 Sync eng/common directory with azure-sdk-tools for PR 1852
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#977 Fix Package.swift for AzureCommunicationCommon
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/Package.swift
Labels: Communication

#983 Create podspecs for AzureIdentity and AzureStorageBlob. Update AzureSDKDemoSwift.
  Podfile
  examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
  examples/AzureSDKDemoSwift/Podfile
  examples/AzureSDKDemoSwiftUI/AzureSDKDemoSwiftUI.xcodeproj/project.pbxproj
  examples/AzureStorageBlobDemo/AzureStorageBlobDemo.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/identity/AzureIdentity/AzureIdentity.podspec.json
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.podspec.json
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
Labels: Storage, Azure.Identity

#986 Sync eng/common directory with azure-sdk-tools for PR 1866
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#987 Improve JSON serialization of optional types.
  sdk/core/AzureCore/Source/Util/RequestString.swift
Labels: Azure.Core

#989 Sync eng/common directory with azure-sdk-tools for PR 1894
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#988 Sync eng/common directory with azure-sdk-tools for PR 1876
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#993 Sync eng/common directory with azure-sdk-tools for PR 1884
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: EngSys, Central-EngSys

#992 Sync eng/common directory with azure-sdk-tools for PR 1902
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#991 Sync eng/common directory with azure-sdk-tools for PR 1887
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#990 Sync eng/common directory with azure-sdk-tools for PR 1901
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#994 Sync eng/common directory with azure-sdk-tools for PR 1909
  eng/common/scripts/common.ps1
  eng/common/scripts/trust-proxy-certificate.ps1
  eng/common/testproxy/apply-dev-cert.sh
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/dotnet-devcert.crt
  eng/common/testproxy/dotnet-devcert.pfx
  eng/common/testproxy/localhost.conf
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#995 Sync eng/common directory with azure-sdk-tools for PR 1913
  eng/common/scripts/Create-APIReview.ps1
Labels: EngSys, Central-EngSys

#996 Sync eng/common directory with azure-sdk-tools for PR 1919
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: EngSys, Central-EngSys

#997 Sync eng/common directory with azure-sdk-tools for PR 1912
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#999 Sync eng/common directory with azure-sdk-tools for PR 1924
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#1001 Sync eng/common directory with azure-sdk-tools for PR 1926
  eng/common/Update-Change-Log.ps1
Labels: EngSys, Central-EngSys

#998 Sync eng/common directory with azure-sdk-tools for PR 1918
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1010 Sync eng/common directory with azure-sdk-tools for PR 1943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1012 Sync eng/common directory with azure-sdk-tools for PR 1952
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: EngSys, Central-EngSys

#1013 Sync eng/common directory with azure-sdk-tools for PR 1953
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
