Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-09, with the labels that each got.

#1009 AzureCommunicationChat 1.0.2 patch
  Podfile
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatClientInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptionsInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
Labels: Communication

#1015 Sync eng/common directory with azure-sdk-tools for PR 1967
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: EngSys, Central-EngSys

#1016 Sync eng/common directory with azure-sdk-tools for PR 1972
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#1014 Release AzureCore 1.0.0-beta.13
  examples/AzureSDKDemoSwift/Podfile
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCore.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.podspec.json
  sdk/storage/AzureStorageBlob/AzureStorageBlob.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/Package.swift
Labels: Communication, Storage, Azure.Core, Azure.Identity

#1021 Update GA patch for preview6
  examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
Labels: Communication

#1019 Apply AzureCommunicationChat hotfix 1.0.2
  Podfile
  examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatClientInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptionsInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
Labels: Communication

#1022 Sync eng/common directory with azure-sdk-tools for PR 1986
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#1026 Sync eng/common directory with azure-sdk-tools for PR 1977
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1025 Sync eng/common directory with azure-sdk-tools for PR 1995
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1028 AzureCommunicationCalling SDK version 2.0.1-beta.1 release
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1027 Sync eng/common directory with azure-sdk-tools for PR 1983
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: EngSys, Central-EngSys

#1029 Sync eng/common directory with azure-sdk-tools for PR 1946
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#1030 Sync eng/common directory with azure-sdk-tools for PR 2006
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#1031 Sync eng/common directory with azure-sdk-tools for PR 1979
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1033 Sync eng/common directory with azure-sdk-tools for PR 2008
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1032 Sync eng/common directory with azure-sdk-tools for PR 2009
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
Labels: EngSys, Central-EngSys

#1035 Sync eng/common directory with azure-sdk-tools for PR 2016
  eng/common/pipelines/templates/steps/verify-changelog.yml
Labels: EngSys, Central-EngSys

#1034 Sync eng/common directory with azure-sdk-tools for PR 2011
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1036 Sync eng/common directory with azure-sdk-tools for PR 2010
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1037 Sync eng/common directory with azure-sdk-tools for PR 2025
  eng/common/scripts/Collect-ChangeLogs.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1040 Sync eng/common directory with azure-sdk-tools for PR 2035
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1042 Sync eng/common directory with azure-sdk-tools for PR 2031
  eng/common/pipelines/templates/steps/policheck.yml
Labels: EngSys, Central-EngSys

#1039 Sync eng/common directory with azure-sdk-tools for PR 2027
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1041 Sync eng/common directory with azure-sdk-tools for PR 2039
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1044 Sync eng/common directory with azure-sdk-tools for PR 2046
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1045 AzureCommunicationChat 1.1.0-beta.1
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1047 Add AzureTest as dependency in Package.swift
  sdk/communication/AzureCommunicationChat/Package.swift
Labels: Communication

#1048 AzureCommunicationChat 1.1.0-beta.2
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication
