Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-03, with the labels that each got.

#739 Sync eng/common directory with azure-sdk-tools for PR 1456
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#744 Sync eng/common directory with azure-sdk-tools for PR 1459
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#746 Sync eng/common directory with azure-sdk-tools for PR 1467
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#745 Sync eng/common directory with azure-sdk-tools for PR 1465
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: Central-EngSys, EngSys

#740 Sync eng/common directory with azure-sdk-tools for PR 1448
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#747 Sync eng/common directory with azure-sdk-tools for PR 1461
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#749 Sync eng/common directory with azure-sdk-tools for PR 1470
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#750 Sync eng/common directory with azure-sdk-tools for PR 1472
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: Central-EngSys, EngSys

#751 Sync eng/common directory with azure-sdk-tools for PR 1452
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#756 Sync eng/common directory with azure-sdk-tools for PR 1479
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#754 Beta 9 version bump
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec.json
  AzureCore.podspec.json
  CHANGELOG.md
  README.md
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCommunication.yml
  jazzy/AzureCommunicationChat.yml
  jazzy/AzureCore.yml
  jazzy/AzureIdentity.yml
  jazzy/AzureStorageBlob.yml
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#761 Sync eng/common directory with azure-sdk-tools for PR 1485
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#763 [Communication] - Identifiers - Init for user and unknown dropping _
  CHANGELOG.md
  sdk/communication/AzureCommunication/Source/Identifiers.swift
Labels: Communication, breaking-change

#753 Sync eng/common directory with azure-sdk-tools for PR 1458
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#766 Sync eng/common directory with azure-sdk-tools for PR 1490
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: Central-EngSys, EngSys

#736 Sync eng/common directory with azure-sdk-tools for PR 1418
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#768 Sync eng/common directory with azure-sdk-tools for PR 1496
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#769 Sync eng/common directory with azure-sdk-tools for PR 1463
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#770 Sync eng/common directory with azure-sdk-tools for PR 1498
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#771 Sync eng/common directory with azure-sdk-tools for PR 1489
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#773 [Communication] - ArchBoard - Resolving issues brought up from arch review
  CHANGELOG.md
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunication/Source/Authentication/AutoRefreshTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
  sdk/communication/AzureCommunication/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
  sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Token/PolicyTokenCredential.swift
  sdk/communication/AzureCommunicationChat/Tests/PolicyTokenCredentialTests.swift
Labels: Communication, breaking-change

#774 Sync eng/common directory with azure-sdk-tools for PR 1502
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#775 [Communication] - Chat - Refactor of class name
  CHANGELOG.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Token/TokenCredentialAdapter.swift
  sdk/communication/AzureCommunicationChat/Tests/PolicyTokenCredentialTests.swift
Labels: Communication

#777 [Communication] - TokenRefresher - Rename typealias
  CHANGELOG.md
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
Labels: Communication

#778 Sync eng/common directory with azure-sdk-tools for PR 1476
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#779 Sync eng/common directory with azure-sdk-tools for PR 1514
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#781 Sync eng/common directory with azure-sdk-tools for PR 1517
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#782 Sync eng/common directory with azure-sdk-tools for PR 1478
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#783 Sync eng/common directory with azure-sdk-tools for PR 1493
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#776 Sync eng/common directory with azure-sdk-tools for PR 1508
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#785 Sync eng/common directory with azure-sdk-tools for PR 1521
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#784 Sync eng/common directory with azure-sdk-tools for PR 1477
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#788 [README] - Communication - Code samples in read me
  sdk/communication/AzureCommunication/README.md
Labels: Communication

#790 Sync eng/common directory with azure-sdk-tools for PR 1527
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys
