Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-07, with the labels that each got.

#941 Sync eng/common directory with azure-sdk-tools for PR 1768
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: Central-EngSys, EngSys

#942 Sync eng/common directory with azure-sdk-tools for PR 1772
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#940 ACS Calling Release 1.1.0
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#945 Sync eng/common directory with azure-sdk-tools for PR 1782
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#944 Sync eng/common directory with azure-sdk-tools for PR 1767
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#926 AzureCommunicationChat GA Feedback
  AzureSDK.xcworkspace/contents.xcworkspacedata
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/IdentifierSerializerTests.swift
Labels: Communication

#947 Sync eng/common directory with azure-sdk-tools for PR 1780
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#948 GA feedback
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsRequestInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContentInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadPropertiesInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CommunicationIdentifierModelInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/UpdateChatThreadRequestInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessageReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatParticipant.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadProperties.swift
  sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/IdentifierSerializerTests.swift
Labels: Communication

#949 Fix update message example in Chat README
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#953 Sync eng/common directory with azure-sdk-tools for PR 1808
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: Central-EngSys, EngSys

#952 ACS Calling Release 2.0.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: APIChange, ArchApproved, Communication, breaking-change

#934 Sync eng/common directory with azure-sdk-tools for PR 1748
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#957 Azure communication chat 1.0.0
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#965 Sync eng/common directory with azure-sdk-tools for PR 1827
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#961 ChatClient set default applicationId to empty string + add missing signaling init step
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
Labels: Communication

#968 AzureCommunicationChat 1.0.1
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#969 Sync eng/common directory with azure-sdk-tools for PR 1848
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/partials/head.tmpl.partial
Labels: Central-EngSys, EngSys

#970 Sync eng/common directory with azure-sdk-tools for PR 1847
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#973 Sync eng/common directory with azure-sdk-tools for PR 1851
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: Central-EngSys, EngSys

#978 Restore test-resources.json
  sdk/communication/test-resources.json
Labels: Communication

#979 Fix up Chat Tests
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
Labels: Communication
