Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-06, with the labels that each got.

#868 Sync eng/common directory with azure-sdk-tools for PR 1611
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#875 Fix build issues with enum CodingKeys
  AzureSDK.xcworkspace/contents.xcworkspacedata
  sdk/core/AzureCore/Tests/XMLModelTests.swift
  sdk/storage/AzureStorageBlob/Source/Models/StorageError.swift
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
Labels: Storage

#881 Sync eng/common directory with azure-sdk-tools for PR 1658
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#876 Add SPM publishing to release pipeline
  eng/pipelines/templates/stages/archetype-ios-release.yml
  eng/scripts/Publish-SwiftPackage.ps1
  sdk/communication/ci.yml
  sdk/core/ci.yml
  sdk/identity/ci.yml
  sdk/storage/ci.yml
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/ci.yml
Labels: Azure.Core, Azure.Identity, Communication, Storage

#883 Updated changelog and podspec for ACS Calling release 1.1.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#872 Remove Any type in TrouterEventUtil
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEventUtil.swift
Labels: Communication

#874 Sync eng/common directory with azure-sdk-tools for PR 1645
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#884 Sync eng/common directory with azure-sdk-tools for PR 1654
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#889 Release AzureCommunicationChat 1.0.0-beta.12
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#890 Fix duplication release stage name
  eng/pipelines/templates/stages/archetype-ios-release.yml
Labels: Central-EngSys, EngSys

#891 Fix communications release pipeline
  eng/pipelines/templates/stages/archetype-ios-release.yml
Labels: Central-EngSys, EngSys

#893 Sync eng/common directory with azure-sdk-tools for PR 1633
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#895 Sync eng/common directory with azure-sdk-tools for PR 1685
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#896 AzureTest playback mode based on TEST_MODE
  AzureSDK.xcworkspace/contents.xcworkspacedata
  Podfile
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/test/AzureTest/DVRSessionTransport.swift
Labels: Communication

#903 Update DVR references to point to fork rather than venmo
  Podfile
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
  sdk/test/AzureTest/Package.swift
Labels: Communication

#904 Recordings on a per-test basis
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
Labels: Communication

#905 AzureCommunicationCommon 1.0.1
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/Package.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/JwtTokenParser.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/StaticTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierTest.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationTokenCredentialTests.swift
Labels: Communication

#910 Sync eng/common directory with azure-sdk-tools for PR 1688
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#907 Feature/recording location
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme
  sdk/test/AzureTest/DVRSessionTransport.swift
Labels: Communication

#909 Env Variable TEST_MODE works as expected
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/test/AzureTest/DVRSessionTransport.swift
Labels: Communication

#912 Automated means of creating test resources
  AzureSDK.xcworkspace/contents.xcworkspacedata
  Podfile
  eng/scripts/prepare_chat_tests.py
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/communication/test-resources-post.ps1
  sdk/communication/test-resources.bicep
  sdk/communication/test-resources.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/AzureTemplate/Tests/AzureTemplateTests.swift
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
  sdk/test/AzureTest/AzureTest.xcodeproj/xcshareddata/xcschemes/AzureTest.xcscheme
  sdk/test/AzureTest/AzureTestTests.swift
  sdk/test/AzureTest/DVRSessionTransport.swift
  sdk/test/AzureTest/Package.swift
  sdk/test/AzureTest/ResourceUtilityClient.swift
  sdk/test/AzureTest/ResourceUtilityClientOptions.swift
Labels: Azure.Core, Communication

#915 Add main to CI files.
  sdk/communication/ci.yml
  sdk/core/ci.yml
  sdk/identity/ci.yml
  sdk/storage/ci.yml
  sdk/template/ci.yml
Labels: Azure.Core, Azure.Identity, Communication, Storage

#913 Add live test pipeline config boilerplate
  eng/pipelines/templates/jobs/live.tests.yml
  eng/pipelines/templates/stages/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/platform-matrix.json
Labels: Central-EngSys

#917 Sync eng/common directory with azure-sdk-tools for PR 1711
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#919 Fix (os/kern) invalid host bug
  sdk/communication/AzureCommunicationChat/Tests/test-settings.plist
Labels: Azure.Core, Communication

#920 Sync eng/common directory with azure-sdk-tools for PR 1716
  eng/common/README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#921 Sync eng/common directory with azure-sdk-tools for PR 1719
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#922 Sync eng/common directory with azure-sdk-tools for PR 1729
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#927 Sync eng/common directory with azure-sdk-tools for PR 1736
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#931 Sync eng/common directory with azure-sdk-tools for PR 1739
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#930 Update master to main
  .github/CODEOWNERS
  README.md
  eng/pipelines/ci.yml
  examples/AzureFunctionSASTokenVendor/README.md
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/README.md
  sdk/communication/ci.yml
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/README.md
  sdk/core/ci.yml
  sdk/identity/ci.yml
  sdk/storage/AzureStorageBlob/README.md
  sdk/storage/ci.yml
  sdk/template/AzureTemplate/README.md
  sdk/template/ci.yml
Labels: Azure.Core, Azure.Identity, Communication, Storage

#924 Injectable test settings
  .gitignore
  Podfile
  eng/scripts/prepare_chat_tests.py
  sdk/communication/AzureCommunicationCalling/README.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/TestSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Util.swift
  sdk/communication/AzureCommunicationChat/Tests/test-settings.plist
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/README.md
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/README.md
  sdk/storage/AzureStorageBlob/README.md
  sdk/test/AzureTest/AzureTest.podspec.json
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
  sdk/test/AzureTest/DVRSessionTransport.swift
  sdk/test/AzureTest/README.md
  sdk/test/AzureTest/TestSettings.swift
Labels: Azure.Core, Communication

#933 Fix CI issues
  AzureSDK.xcworkspace/contents.xcworkspacedata
  Podfile
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterSettings.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/events/chat.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Util.swift
Labels: Azure.Core

#935 Scrub headings and commit chat test recordings.
  Podfile
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/test/AzureTest/DVRSessionTransport.swift
Labels: Communication

#937 Sync eng/common directory with azure-sdk-tools for PR 1725
  eng/common/pipelines/templates/steps/enable-long-path-support.yml
  eng/common/pipelines/templates/steps/set-daily-docs-branch-name.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Save-Package-Properties.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#938 Sync eng/common directory with azure-sdk-tools for PR 1759
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: Central-EngSys, EngSys

#939 Sync eng/common directory with azure-sdk-tools for PR 1763
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys
