Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-01, with the labels that each got.

#612 [Communication] - Identifiers - Arch review board adding identifiers suffix
  examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
Labels: Azure.Core, Communication

#618 Sync eng/common directory with azure-sdk-tools for PR 1299
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#621 Sync eng/common directory with azure-sdk-tools for PR 1278
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#620 Sync eng/common directory with azure-sdk-tools for PR 1298
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#625 Sync eng/common directory with azure-sdk-tools for PR 1302
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#624 Sync eng/common directory with azure-sdk-tools for PR 1301
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#623 Adding more tests for Chat SDK
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/RecordingUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/createThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listMessages.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listThreads.json
  sdk/communication/AzureCommunicationChat/Tests/Util/TestUtil.swift
Labels: Communication

#627 Sync eng/common directory with azure-sdk-tools for PR 1306
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#626 Latest swagger updates for Chat SDK
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Source/Generated/AzureCommunicationChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThreadOperation.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsErrors.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipant.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadInfo.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadsInfoCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/Enumerations.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendChatMessageResult.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Swagger/swagger.json
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/CreateThreadResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/GetMessageResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/GetThreadResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListMessagesResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListParticipantsResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListReadReceiptResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListThreadsResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/SendMessageResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/RecordingUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/createThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/getMessage.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/getThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listMessages.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listThreads.json
Labels: Communication

#615 [Communication] - Auth - Introducing CommunicationTokenRefreshOptions
  CHANGELOG.md
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
  sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m
Labels: Communication

#628 Sync eng/common directory with azure-sdk-tools for PR 1308
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#630 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#631 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#635 Sync eng/common directory with azure-sdk-tools for PR 1314
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#636 Increment versions for release 1.0.0-beta.7
  .jazzy/AzureCommunication.yml
  .jazzy/AzureCommunicationChat.yml
  .jazzy/AzureCore.yml
  .jazzy/AzureIdentity.yml
  .jazzy/AzureStorageBlob.yml
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec.json
  AzureCore.podspec.json
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Azure.Core, Azure.Identity, Communication, Storage

#638 Updates from newer linter / tooling
  AzureCommunicationCalling.podspec.json
  Podfile.lock
  sdk/core/AzureCore/Source/ClientLogger.swift
  sdk/core/AzureCore/Source/DataStructures/XMLModel.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineStage.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/AuthenticationPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/HTTPHeader.swift
  sdk/core/AzureCore/Source/Providers/DeviceProviders.swift
  sdk/core/AzureCore/Source/Providers/PlatformInfoProvider.swift
  sdk/core/AzureCore/Source/Util/ApplicationUtil.swift
  sdk/core/AzureCore/Source/Util/AzureCodable.swift
  sdk/core/AzureCore/Source/Util/ConvertingInitializers.swift
  sdk/core/AzureCore/Source/Util/CryptoUtil.swift
  sdk/core/AzureCore/Source/Util/RequestString.swift
  sdk/core/AzureCore/Source/Util/StringUtil.swift
  sdk/core/AzureCore/Source/Util/URLUtil.swift
  sdk/core/AzureCore/Tests/Stubs/HTTPHeaderStub.swift
  sdk/core/AzureCore/Tests/Stubs/PipelineStubs.swift
  sdk/core/AzureCore/Tests/UserAgentPolicyTests.swift
Labels: Azure.Core

#592 StorageStreamUploader fix for SharedKeyCredentials (issue #585)
  sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
Labels: Storage

#640 [Communication] - Identifiers - Teams property renamed to userId
  CHANGELOG.md
  sdk/communication/AzureCommunication/Source/Identifiers.swift
Labels: Communication, breaking-change

#633 [Communication] - Auth - Removing a duplicate policy and replacing it with bearer auth policy
  AzureSDK.xcworkspace/xcshareddata/xcschemes/all.xcscheme
  CHANGELOG.md
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationAuthenticationPolicy.swift
  sdk/communication/AzureCommunication/Tests/CommunicationPolicyTokenCredentialTests.swift
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThreadOperation.swift
Labels: Communication, breaking-change

#642 Sync eng/common directory with azure-sdk-tools for PR 1318
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#643 [Communication] Add CommunicationIdentifierSerializer to serialize/deserialize CommunicationIdentifierModel
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierModel.swift
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierSerializer.swift
  sdk/communication/AzureCommunication/Source/Enumerations.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
  sdk/communication/AzureCommunication/Tests/CommunicationIdentifierSerializerTests.swift
Labels: Communication

#647 Sync eng/common directory with azure-sdk-tools for PR 1317
  eng/common/pipelines/templates/steps/get-pr-owners.yml
Labels: Central-EngSys, EngSys

#648 Sync eng/common directory with azure-sdk-tools for PR 1327
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#649 Sync eng/common directory with azure-sdk-tools for PR 1251
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#650 Sync eng/common directory with azure-sdk-tools for PR 1335
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#654 Sync eng/common directory with azure-sdk-tools for PR 1343
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#657 Sync eng/common directory with azure-sdk-tools for PR 1341
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#603 Add AzureStorageBlobDemo and Container commands.
  AzureSDK.xcworkspace/contents.xcworkspacedata
  AzureSDK.xcworkspace/xcshareddata/xcschemes/communication.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/core.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/identity.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/storage.xcscheme
  Podfile
  examples/AzureSDKDemoSwift/AzureSDKDemoSwift.entitlements
  examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/xcshareddata/xcschemes/AzureSDKDemoSwift.xcscheme
  examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
  examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/xcshareddata/xcschemes/AzureSDKSmokeTest.xcscheme
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/ViewController.swift
  examples/AzureStorageBlobDemo/AzureStorageBlobDemo.entitlements
  examples/AzureStorageBlobDemo/AzureStorageBlobDemo.xcodeproj/project.pbxproj
  examples/AzureStorageBlobDemo/AzureStorageBlobDemo.xcodeproj/xcshareddata/xcschemes/AzureStorageBlobDemo.xcscheme
  examples/AzureStorageBlobDemo/Source/AppDelegate.swift
  examples/AzureStorageBlobDemo/Source/Assets.xcassets/AppIcon.appiconset/Contents.json
  examples/AzureStorageBlobDemo/Source/Assets.xcassets/Contents.json
  examples/AzureStorageBlobDemo/Source/Assets.xcassets/logo.imageset/Azure SDK Shirt Design-Blue.png
  examples/AzureStorageBlobDemo/Source/Assets.xcassets/logo.imageset/Contents.json
  examples/AzureStorageBlobDemo/Source/Base.lproj/LaunchScreen.storyboard
  examples/AzureStorageBlobDemo/Source/Base.lproj/Main.storyboard
  examples/AzureStorageBlobDemo/Source/Common.swift
  examples/AzureStorageBlobDemo/Source/LoginViewController.swift
  examples/AzureStorageBlobDemo/Source/MainViewController.swift
  examples/AzureStorageBlobDemo/Source/StorageTests.swift
  examples/AzureStorageBlobDemo/Source/Supporting Files/Info.plist
  sdk/core/AzureCore/Source/DataStructures/XMLMap.swift
  sdk/core/AzureCore/Source/Errors.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineClient.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineStage.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/HTTPResponse.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
  sdk/core/AzureCore/Source/Util/RequestString.swift
  sdk/core/AzureCore/Tests/CollectionsTests.swift
  sdk/core/AzureCore/Tests/Data Files/pagedthings1.json
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASCredential.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASToken.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSharedKeyCredential.swift
  sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift
  sdk/storage/AzureStorageBlob/Source/DataStructures/TransferCollection.swift
  sdk/storage/AzureStorageBlob/Source/Models/ContainerCpkScopeInfo.swift
  sdk/storage/AzureStorageBlob/Source/Models/ContainerProperties.swift
  sdk/storage/AzureStorageBlob/Source/Models/Enumerations.swift
  sdk/storage/AzureStorageBlob/Source/Models/StorageError.swift
  sdk/storage/AzureStorageBlob/Source/Operations/BlobDownloadOperations.swift
  sdk/storage/AzureStorageBlob/Source/Operations/BlobsOperations.swift
  sdk/storage/AzureStorageBlob/Source/Operations/ContainersOperations.swift
  sdk/storage/AzureStorageBlob/Source/Options/ClientMethodOptions.swift
  sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
  sdk/storage/AzureStorageBlob/Source/Transport/StorageHTTPHeader.swift
  sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Labels: Azure.Core, Azure.Identity, Communication, Storage

#656 Chat SDK uses Communication identifiers
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Models/CreateThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Models/CreateThreadResult.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Message.swift
  sdk/communication/AzureCommunicationChat/Source/Models/MessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Participant.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Thread.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/RecordingUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/createThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/getThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listMessages.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listReadReceipts.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listThreads.json
Labels: Communication

#661 Add test for HTML messages
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/TestUtil.swift
Labels: Communication

#660 Chat sets repeatability-Request-ID if its not provided
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
Labels: Communication

#664 Fix typo
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
Labels: Communication

#663 Sync eng/common directory with azure-sdk-tools for PR 1345
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys
