Repository Azure/azure-sdk-for-ios, pull requests merged in 2021-02, with the labels that each got.

#668 Sync eng/common directory with azure-sdk-tools for PR 1351
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#655 Add cloud environment to MicrosoftTeamsIdentifier
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/Source/CommunicationCloudEnvironment.swift
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierModel.swift
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierSerializer.swift
  sdk/communication/AzureCommunication/Source/Enumerations.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
  sdk/communication/AzureCommunication/Tests/CommunicationIdentifierSerializerTests.swift
  sdk/communication/AzureCommunication/Tests/CommunicationIdentifierTest.swift
  sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
Labels: Communication

#670 Sync eng/common directory with azure-sdk-tools for PR 1361
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#671 Sync eng/common directory with azure-sdk-tools for PR 1353
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#672 [Communication] - Identifiers - Fixing ObjC interface
  sdk/communication/AzureCommunication/Source/CommunicationCloudEnvironment.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
Labels: Azure.Core, Communication, Storage

#676 Sync eng/common directory with azure-sdk-tools for PR 1364
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#677 Sync eng/common directory with azure-sdk-tools for PR 1365
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: Central-EngSys, EngSys

#678 Sync eng/common directory with azure-sdk-tools for PR 1366
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#680 Regenerate Chat Preview 2
  sdk/communication/AzureCommunicationChat/Source/Custom.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/AzureCommunicationChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/AzureCommunicationChatService.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatThreadMembersRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadInfo.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadMember.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadMembersCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadsInfoCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/Enumerations.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ErrorType.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/IndividualStatusResponse.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/MultiStatusResponse.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendChatMessageResult.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendReadReceiptRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/UpdateChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/UpdateChatThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+AddChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+GetChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+ListChatThreadMembersOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+RemoveChatThreadMemberOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatService+UpdateChatThreadOptions.swift
Labels: Communication

#684 Fix naming in comments CommunicationUserCredential -> CommunicationTokenCredential
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationPolicyTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
Labels: Communication

#686 [Communication] - Identifiers - rename a id to rawId
  CHANGELOG.md
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierSerializer.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
  sdk/communication/AzureCommunication/Tests/CommunicationIdentifierSerializerTests.swift
  sdk/communication/AzureCommunication/Tests/CommunicationIdentifierTest.swift
Labels: Communication

#689 Sync eng/common directory with azure-sdk-tools for PR 1376
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#692 Add Readme and package.swift back to project
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
Labels: Communication

#697 Bump versions for beta 8.
  AzureCommunication.podspec.json
  AzureCommunicationCalling.podspec.json
  AzureCommunicationChat.podspec.json
  AzureCore.podspec.json
  AzureSDK.xcworkspace/xcshareddata/xcschemes/all.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/communication.xcscheme
  AzureSDK.xcworkspace/xcshareddata/xcschemes/examples.xcscheme
  CHANGELOG.md
  README.md
  eng/ignore-links.txt
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/SceneDelegate.swift
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/ViewController.swift
  examples/AzureSDKSmokeTest/Podfile
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/README.md
  sdk/communication/AzureCommunication/Source/Authentication/AutoRefreshTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationAccessToken.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationPolicyTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredentialProviding.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
  sdk/communication/AzureCommunication/Source/Authentication/JwtTokenParser.swift
  sdk/communication/AzureCommunication/Source/Authentication/StaticTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
  sdk/communication/AzureCommunication/Source/CommunicationCloudEnvironment.swift
  sdk/communication/AzureCommunication/Source/CommunicationIdentifierSerializer.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
  sdk/communication/AzureCommunication/Tests/CommunicationPolicyTokenCredentialTests.swift
  sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThreadOperation.swift
  sdk/communication/AzureCommunicationChat/Source/Models/CreateThreadResult.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Message.swift
  sdk/communication/AzureCommunicationChat/Source/Supporting Files/Info.plist
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Labels: Communication

#700 Bump version in Chat README
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#701 Sync eng/common directory with azure-sdk-tools for PR 1393
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#702 Sync eng/common directory with azure-sdk-tools for PR 1303
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#703 Sync eng/common directory with azure-sdk-tools for PR 1358
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#658 [Communication] - Tests - Reenable the objc unit tests
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m
Labels: Communication

#706 Add Jazzy YML to the SDK Workspace
  AzureSDK.xcworkspace/contents.xcworkspacedata
  Scripts/build_api_docs.sh
  jazzy/AzureCommunication.yml
  jazzy/AzureCommunicationChat.yml
  jazzy/AzureCore.yml
  jazzy/AzureIdentity.yml
  jazzy/AzureStorageBlob.yml
  jazzy/index.html.erb
Labels: EngSys

#704 Sync eng/common directory with azure-sdk-tools for PR 1386
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#708 Sync eng/common directory with azure-sdk-tools for PR 1307
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#710 Sync eng/common directory with azure-sdk-tools for PR 1401
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#711 Sync eng/common directory with azure-sdk-tools for PR 1405
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#712 Sync eng/common directory with azure-sdk-tools for PR 1408
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#694 Sync eng/common directory with azure-sdk-tools for PR 1371
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#713 Sync eng/common directory with azure-sdk-tools for PR 1374
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#722 Sync eng/common directory with azure-sdk-tools for PR 1396
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#719 Sync eng/common directory with azure-sdk-tools for PR 1415
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#724 Sync eng/common directory with azure-sdk-tools for PR 1425
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#717 Chat preview4 communication identifier changes
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/AzureCommunicationChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThreadOperation.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsErrors.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/AddChatParticipantsRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessagesCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipant.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CommunicationError.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CommunicationIdentifierModel.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadErrors.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CreateChatThreadRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/Enumerations.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+GetChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+UpdateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Models/CreateThreadResult.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Message.swift
  sdk/communication/AzureCommunicationChat/Source/Models/MessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Participant.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ReadReceipt.swift
  sdk/communication/AzureCommunicationChat/Source/Models/Thread.swift
  sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift
  sdk/communication/AzureCommunicationChat/Swagger/swagger.json
  sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/CreateThreadResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/GetMessageResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/GetThreadResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListMessagesResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListParticipantsResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Mocks/ListReadReceiptResponse.json
  sdk/communication/AzureCommunicationChat/Tests/Util/RecordingUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/createThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/getThread.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listMessages.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listReadReceipts.json
  sdk/communication/AzureCommunicationChat/Tests/Util/Recordings/listThreads.json
Labels: Communication

#725 Sync eng/common directory with azure-sdk-tools for PR 1429
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#727 Sync eng/common directory with azure-sdk-tools for PR 1436
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#726 Sync eng/common directory with azure-sdk-tools for PR 1428
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#723 Update SmokeTest for use on CI
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj
  examples/AzureSDKSmokeTest/Podfile
Labels: EngSys

#728 Sync eng/common directory with azure-sdk-tools for PR 1421
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: Central-EngSys, EngSys

#730 [Communication] - Documentation - Update docs
  .swiftlint.yml
  sdk/communication/AzureCommunication/Source/Authentication/AutoRefreshTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationAccessToken.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredentialProviding.swift
  sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
  sdk/communication/AzureCommunication/Source/Authentication/StaticTokenCredential.swift
  sdk/communication/AzureCommunication/Source/Identifiers.swift
Labels: Communication

#735 Sync eng/common directory with azure-sdk-tools for PR 1447
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: Central-EngSys, EngSys
