Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-11, with the labels that each got.

#1373 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1372 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1375 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1374 Sync eng/common directory with azure-sdk-tools for PR 4586
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1376 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#1378 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1379 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#1381 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1382 AzureCommunicationCaling-2.3.0-beta.2
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1384 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#1386 Sync eng/common directory with azure-sdk-tools for PR 4623
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1387 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1388 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1392 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1391 Fix the phonenumber serialization
  sdk/communication/AzureCommunicationCommon/Source/Identifiers.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierTest.swift
  sdk/communication/AzureCommunicationCommon/Tests/CreateCommunicationIdentifier.swift
Labels: Communication

#1394 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#1395 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#1396 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1390 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#1398 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#1397 A patch release for AzureCommunicationCommon 1.1.1
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
Labels: Communication

#1402 Disabled flaky tests of the AzureCommunicationCommon
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
Labels: Communication

#1406 Sync eng/common directory with azure-sdk-tools for PR 4713
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
