Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-09, with the labels that each got.

#1341 Sync eng/common directory with azure-sdk-tools for PR 4042
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#1342 AzureCommunicationCalling-2.4.0-alpha.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
Labels: Communication

#1343 Add github actions based check enforcer
  .github/workflows/event.yml
Labels: Central-EngSys

#1344 [Project] Remove the obj-c api and tests
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/Source/CommunicationIdentifierFactory.h
  sdk/communication/AzureCommunicationCommon/Source/CommunicationIdentifierFactory.m
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierFactoryTests.m
Labels: Communication

#1339 Release AzureCommunicationCommon 1.1.0
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
Labels: Communication

#1335 Push Notification GA release
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/NotificationUtils/IdentityUtil.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/AppGroupPushNotificationKeyStorage.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationBaseEvent.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationKeyStorage.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StartPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StopPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_deleteRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_setRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
Labels: Communication

#1345 Azure communication chat 1.3.0 Release
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1346 Sync eng/common directory with azure-sdk-tools for PR 4128
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1347 Sync eng/common directory with azure-sdk-tools for PR 4098
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1349 Sync eng/common directory with azure-sdk-tools for PR 4141
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: EngSys, Central-EngSys

#1348 Update check enforcer yaml permissions and name
  .github/workflows/event.yml
Labels: Central-EngSys

#1350 Sync eng/common directory with azure-sdk-tools for PR 4169
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1351 Sync eng/common directory with azure-sdk-tools for PR 4212
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1352 Sync eng/common directory with azure-sdk-tools for PR 4240
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys
