Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-02, with the labels that each got.

#1143 Sync eng/common directory with azure-sdk-tools for PR 2608
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1142 Sync eng/common directory with azure-sdk-tools for PR 2605
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1145 Sync eng/common directory with azure-sdk-tools for PR 2673
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1144 Sync eng/common directory with azure-sdk-tools for PR 2668
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#1147 Sync eng/common directory with azure-sdk-tools for PR 2682
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1148 Sync eng/common directory with azure-sdk-tools for PR 2685
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1149 Sync eng/common directory with azure-sdk-tools for PR 2691
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#1151 Fix broken onError chain in AzureCore
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
Labels: Azure.Core

#1153 Sync eng/common directory with azure-sdk-tools for PR 2686
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1155 Sync eng/common directory with azure-sdk-tools for PR 2720
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1150 Sync eng/common directory with azure-sdk-tools for PR 2679
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#1156 Sync eng/common directory with azure-sdk-tools for PR 2721
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1158 Sync eng/common directory with azure-sdk-tools for PR 2733
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1159 Prepare AzureCore 1.0.0-beta.14
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCore.yml
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/README.md
Labels: Azure.Core

#1161 Sync eng/common directory with azure-sdk-tools for PR 2739
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1162 Sync eng/common directory with azure-sdk-tools for PR 2740
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1165 Sync eng/common directory with azure-sdk-tools for PR 2754
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1163 Sync eng/common directory with azure-sdk-tools for PR 2741
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1164 Sync eng/common directory with azure-sdk-tools for PR 2758
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1167 Sync eng/common directory with azure-sdk-tools for PR 2759
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1157 Add Gcch Support for iOS Signaling Client
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/TestSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterSettingsUnitTest.swift
Labels: Communication

#1174 Fix the DVR live tests recordings
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/communication/AzureCommunicationChat/Tests/TestSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterSettingsUnitTest.swift
Labels: Communication

#1177 Sync eng/common directory with azure-sdk-tools for PR 2805
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1178 Sync eng/common directory with azure-sdk-tools for PR 2808
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1181 Sync eng/common directory with azure-sdk-tools for PR 2771
  eng/common/scripts/copy-from-blobstorage.ps1
Labels: EngSys, Central-EngSys

#1183 [AzureCore] Fix transport callback fallthrough
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
  sdk/test/AzureTest/Source/DVRSessionTransport.swift
Labels: Azure.Core
