Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-07, with the labels that each got.

#1303 Sync eng/common directory with azure-sdk-tools for PR 3428
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1304 Sync eng/common directory with azure-sdk-tools for PR 3577
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#1301 Sync eng/common directory with azure-sdk-tools for PR 3527
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#1305 Sync eng/common directory with azure-sdk-tools for PR 3500
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1307 Sync eng/common directory with azure-sdk-tools for PR 3480
  eng/common/pipelines/templates/steps/validate-filename.yml
Labels: EngSys, Central-EngSys

#1308 Sync eng/common directory with azure-sdk-tools for PR 3546
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#1309 Sync eng/common directory with azure-sdk-tools for PR 3590
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#1310 Sync eng/common directory with azure-sdk-tools for PR 3606
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1313 Sync eng/common directory with azure-sdk-tools for PR 3578
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1315 Sync eng/common directory with azure-sdk-tools for PR 3642
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#1316 Sync eng/common directory with azure-sdk-tools for PR 3657
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1317 Sync eng/common directory with azure-sdk-tools for PR 3656
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1283 Add PushNotificationEncryptionDelegate
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/NotificationUtils/CryptoUtils.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/AppGroupPushNotificationKeyHandler.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationClient.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationKeyHandler.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StartPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StopPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_deleteRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_setRegistration_ReturnsSuccess.json
Labels: Communication, Communication - Chat

#1320 Sync eng/common directory with azure-sdk-tools for PR 3700
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1321 Sync eng/common directory with azure-sdk-tools for PR 3702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1325 Sync eng/common directory with azure-sdk-tools for PR 3661
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1324 Sync eng/common directory with azure-sdk-tools for PR 3735
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1323 Azure communication chat 1.3.0 beta.1
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1326 Sync eng/common directory with azure-sdk-tools for PR 3754
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1327 [Project] Remove Core framework linking
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
Labels: Communication

#1328 Sync eng/common directory with azure-sdk-tools for PR 3753
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#1329 Sync eng/common directory with azure-sdk-tools for PR 3787
  eng/common/TestResources/setup-environments.yml
Labels: EngSys, Central-EngSys
