Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-10, with the labels that each got.

#1353 AzureCommunicationCalling-2.3.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1355 Sync eng/common directory with azure-sdk-tools for PR 4315
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1356 Sync eng/common directory with azure-sdk-tools for PR 4311
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#1359 Add default .assets directory to .gitignore
  .gitignore
Labels: Central-EngSys

#1357 Sync eng/common directory with azure-sdk-tools for PR 4341
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1360 Sync eng/common directory with azure-sdk-tools for PR 4372
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1361 Sync eng/common directory with azure-sdk-tools for PR 3790
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1362 Sync eng/common directory with azure-sdk-tools for PR 4486
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#1364 Sync eng/common directory with azure-sdk-tools for PR 4480
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1367 Sync eng/common directory with azure-sdk-tools for PR 4504
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1368 Sync eng/common directory with azure-sdk-tools for PR 4527
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1370 Sync eng/common directory with azure-sdk-tools for PR 4543
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1369 Sync eng/common directory with azure-sdk-tools for PR 4532
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
