Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-05, with the labels that each got.

#1252 Sync eng/common directory with azure-sdk-tools for PR 3261
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#1253 Sync eng/common directory with azure-sdk-tools for PR 3269
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1254 Sync eng/common directory with azure-sdk-tools for PR 3280
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#1260 Sync eng/common directory with azure-sdk-tools for PR 3320
  eng/common/TestResources/README.md
Labels: EngSys, Central-EngSys

#1259 Sync eng/common directory with azure-sdk-tools for PR 3323
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#1231 Add trouter events
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEventUtil.swift
Labels: Communication

#1263 [CommunicationChat] Azure Communication Chat 1.2.0 Release
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1264 Sync eng/common directory with azure-sdk-tools for PR 3341
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys, Central-EngSys

#1265 Update Changelog with Release Date
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
Labels: Communication

#1267 Update CHANGELOG.md
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
Labels: Communication

#1270 Add TTL for encryption key pair
  sdk/communication/AzureCommunicationChat/Source/NotificationUtils/CryptoUtils.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationClient.swift
  sdk/communication/AzureCommunicationChat/Source/Registrar/RegistrarTransportSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StartPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StopPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_deleteRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_setRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/RegistrarClientTests.swift
Labels: Communication, Communication - Chat

#1273 Define a TTL value for Registration Record
  sdk/communication/AzureCommunicationChat/Source/NotificationUtils/CryptoUtils.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationClient.swift
  sdk/communication/AzureCommunicationChat/Source/Registrar/RegistrarTransportSettings.swift
  sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StartPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_StopPushNotifications_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_deleteRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_setRegistration_ReturnsSuccess.json
  sdk/communication/AzureCommunicationChat/Tests/RegistrarClientTests.swift
Labels: Communication, Communication - Chat

#1276 Sync eng/common directory with azure-sdk-tools for PR 3368
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1275 Sync eng/common directory with azure-sdk-tools for PR 3342
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#1277 Sync eng/common directory with azure-sdk-tools for PR 3362
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys
