Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-03, with the labels that each got.

#1186 Update Chat SDK API Version to 2021-09-07
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/ChatThread.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptionsInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessageContent.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
  sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
Labels: Communication

#1189 Sync eng/common directory with azure-sdk-tools for PR 2778
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys, Central-EngSys

#1190 Sync eng/common directory with azure-sdk-tools for PR 2833
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1192 Updates for SwiftLint and SwiftFormat
  examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
  examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
  examples/AzureStorageBlobDemo/Source/Common.swift
  examples/AzureStorageBlobDemo/Source/MainViewController.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/JwtTokenParser.swift
  sdk/core/AzureCore/Source/DataStructures/XMLMap.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/DataStringConvertible.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
  sdk/core/AzureCore/Source/Util/ReachabilityManager.swift
  sdk/core/AzureCore/Tests/RequestParametersTests.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASCredential.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASToken.swift
  sdk/storage/AzureStorageBlob/Source/Credentials/StorageSharedKeyCredential.swift
  sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift
  sdk/storage/AzureStorageBlob/Source/DataStructures/TransferCollection.swift
  sdk/storage/AzureStorageBlob/Source/Models/ContainerProperties.swift
  sdk/storage/AzureStorageBlob/Source/Operations/BlobDownloadOperations.swift
  sdk/storage/AzureStorageBlob/Source/Operations/BlobUploadOperations.swift
  sdk/storage/AzureStorageBlob/Source/Operations/BlobsOperations.swift
  sdk/storage/AzureStorageBlob/Source/Operations/ContainersOperations.swift
  sdk/storage/AzureStorageBlob/Source/Options/ClientMethodOptions.swift
  sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift
  sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
  sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Labels: Communication, Storage, Azure.Core

#1191 Sync eng/common directory with azure-sdk-tools for PR 2823
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1188 Sync eng/common directory with azure-sdk-tools for PR 2830
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#1195 Sync eng/common directory with azure-sdk-tools for PR 2824
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#1198 Sync eng/common directory with azure-sdk-tools for PR 2875
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1199 Release AzureCore 1.0.0-beta.15
  jazzy/AzureCore.yml
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/README.md
Labels: Azure.Core

#1179 Sync eng/common directory with azure-sdk-tools for PR 2810
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#1200 Sync eng/common directory with azure-sdk-tools for PR 2889
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1201 Sync eng/common directory with azure-sdk-tools for PR 2892
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1194 Sync eng/common directory with azure-sdk-tools for PR 2836
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#1202 Sync eng/common directory with azure-sdk-tools for PR 2899
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#1204 FIX gcch acs not supported issue
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/TrouterEventUtil.swift
  sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
  sdk/test/AzureTest/Source/DVRSessionTransport.swift
Labels: Communication

#1205 Bump up the chat version
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1208 Release AzureCommunicationCommon 1.0.3
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
Labels: Communication

#1209 Sync eng/common directory with azure-sdk-tools for PR 2910
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1212 Sync eng/common directory with azure-sdk-tools for PR 2870
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#1213 Sync eng/common directory with azure-sdk-tools for PR 2866
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1214 Sync eng/common directory with azure-sdk-tools for PR 2901
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1215 Sync eng/common directory with azure-sdk-tools for PR 2922
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1216 Add 2021-04-05-preview6 back
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
Labels: Communication

#1217 Sync eng/common directory with azure-sdk-tools for PR 2847
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1218 Sync eng/common directory with azure-sdk-tools for PR 2928
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1219 Remove preview version
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
Labels: Communication

#1220 Sync eng/common directory with azure-sdk-tools for PR 2939
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1221 Sync eng/common directory with azure-sdk-tools for PR 2938
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1210 Sync eng/common directory with azure-sdk-tools for PR 2861
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/get-changedfiles.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#1222 Sync eng/common directory with azure-sdk-tools for PR 2972
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Helpers/git-helpers.ps1
Labels: EngSys, Central-EngSys

#1224 Sync eng/common directory with azure-sdk-tools for PR 2979
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys
