Repository Azure/azure-sdk-for-ios, pull requests merged in 2022-12, with the labels that each got.

#1409 Sync eng/common directory with azure-sdk-tools for PR 4856
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: EngSys, Central-EngSys

#1400 [Feature] Provide async wrappers for PagedCollection
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/Source/DataStructures/Collections.swift
  sdk/core/AzureCore/Tests/CollectionsTests.swift
Labels: Azure.Core

#1412 Sync eng/common directory with azure-sdk-tools for PR 4878
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1415 Fix CI
  eng/scripts/swiftlint.sh
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/SceneDelegate.swift
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageContentInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatMessageReadReceiptsCollection.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatParticipantInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadItem.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/ChatThreadPropertiesInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/CommunicationIdentifierModelInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendChatMessageRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Models/SendTypingNotificationRequest.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AddChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/AzureCommunicationChatClientOptionsInternal.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/CreateChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/DeleteChatThreadOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/GetChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatMessagesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatParticipantsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatReadReceiptsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatThreadsOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/RemoveChatParticipantOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendChatReadReceiptOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/SendTypingNotificationOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatMessageOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Generated/Options/UpdateChatThreadPropertiesOptions.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatMessage.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatParticipant.swift
  sdk/communication/AzureCommunicationChat/Source/Models/ChatThreadProperties.swift
  sdk/communication/AzureCommunicationChat/Source/NotificationUtils/IdentityUtil.swift
  sdk/communication/AzureCommunicationChat/Source/Options/AzureCommunicationChatClientOptions.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationBaseEvent.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationClient.swift
  sdk/communication/AzureCommunicationChat/Source/PushNotification/PushNotificationKeyStorage.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterSettings.swift
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/Source/Identifiers.swift
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/Source/DataStructures/Collections.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
  sdk/core/AzureCore/Source/Util/ReachabilityManagerType.swift
  sdk/core/AzureCore/Tests/CollectionsTests.swift
  sdk/core/AzureCore/Tests/XMLModelTests.swift
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
Labels: Communication

#1417 Sync eng/common directory with azure-sdk-tools for PR 4813
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#1418 Sync eng/common directory with azure-sdk-tools for PR 4930
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#1421 Sync eng/common directory with azure-sdk-tools for PR 4944
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1420 Sync eng/common directory with azure-sdk-tools for PR 4514
  eng/common/scripts/Verify-AgentOS.ps1
Labels: EngSys, Central-EngSys

#1424 Sync eng/common directory with azure-sdk-tools for PR 4962
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#1423 Sync eng/common directory with azure-sdk-tools for PR 4940
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1425 Sync eng/common directory with azure-sdk-tools for PR 4988
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1427 Sync eng/common directory with azure-sdk-tools for PR 4998
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#1426 Sync eng/common directory with azure-sdk-tools for PR 4880
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#1428 Sync eng/common directory with azure-sdk-tools for PR 4985
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1432 AzureCommunicationCalling_2.2.2
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1434 AzureCommunicationCalling_2.3.0-beta.3
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication
