Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-02, with the labels that each got.

#1463 Sync eng/common directory with azure-sdk-tools for PR 4812
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#1461 Sync eng/common directory with azure-sdk-tools for PR 5291
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
  eng/ignore-links.txt
Labels: EngSys, Central-EngSys

#1464 Sync eng/common directory with azure-sdk-tools for PR 5313
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1465 Sync eng/common directory with azure-sdk-tools for PR 5309
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1467 Sync eng/common directory with azure-sdk-tools for PR 5316
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#1456 Introducing a public cancel API for the CommunicationTokenCredential
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/README.md
  sdk/communication/AzureCommunicationCommon/Source/Authentication/AutoRefreshTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredentialProviding.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/StaticTokenCredential.swift
  sdk/communication/AzureCommunicationCommon/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshOnDemandTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshProactiveTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCAutoRefreshOnDemandTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCAutoRefreshProactiveTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCCommunicationTokenCredentialTests.h
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCStaticTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/StaticTokenCredentialTests.swift
Labels: Communication, Communication - Identity

#1469 Sync eng/common directory with azure-sdk-tools for PR 5083
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1471 Sync eng/common directory with azure-sdk-tools for PR 5412
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys, Central-EngSys

#1470 Update `CODEOWNERS` paths: fix invalid paths
  .github/CODEOWNERS
Labels: Central-EngSys

#1473 Sync eng/common directory with azure-sdk-tools for PR 5427
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#1474 Sync eng/common directory with azure-sdk-tools for PR 5437
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1475 Sync eng/common directory with azure-sdk-tools for PR 5456
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1476 Sync eng/common directory with azure-sdk-tools for PR 5103
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1477 Sync eng/common directory with azure-sdk-tools for PR 5493
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#1479 Sync eng/common directory with azure-sdk-tools for PR 5531
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1480 Sync eng/common directory with azure-sdk-tools for PR 5537
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys

#1472 Sync eng/common directory with azure-sdk-tools for PR 5431
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1481 Sync eng/common directory with azure-sdk-tools for PR 5562
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1483 Sync eng/common directory with azure-sdk-tools for PR 5568
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
Labels: EngSys, Central-EngSys
