Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-06, with the labels that each got.

#1552 Sync eng/common directory with azure-sdk-tools for PR 6273
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1553 Sync .github/workflows directory with azure-sdk-tools for PR 6280
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1554 Sync eng/common directory with azure-sdk-tools for PR 6272
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/TypeSpec-Project-Process.ps1
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#1555 Sync eng/common directory with azure-sdk-tools for PR 6293
  eng/common/scripts/TypeSpec-Project-Process.ps1
Labels: EngSys, Central-EngSys

#1556 Sync eng/common directory with azure-sdk-tools for PR 6304
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#1557 Sync eng/common directory with azure-sdk-tools for PR 6305
  eng/common/scripts/TypeSpec-Project-Process.ps1
Labels: EngSys, Central-EngSys

#1558 Sync eng/common directory with azure-sdk-tools for PR 6333
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1559 release AzureCommunicationCalling 2.4.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1561 Sync eng/common directory with azure-sdk-tools for PR 6300
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
Labels: EngSys, Central-EngSys

#1563 Sync eng/common directory with azure-sdk-tools for PR 6392
  eng/common/pipelines/templates/steps/create-pull-request.yml
Labels: EngSys, Central-EngSys

#1566 Sync eng/common directory with azure-sdk-tools for PR 6434
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1567 Sync eng/common directory with azure-sdk-tools for PR 6440
  eng/common/scripts/get-codeowners.lib.ps1
Labels: EngSys, Central-EngSys

#1568 Sync .github/workflows directory with azure-sdk-tools for PR 6440
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1530 Support spaces in the build scripts
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
Labels: no-recent-activity, Azure.Core, Communication - Common
