Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-01, with the labels that each got.

#1436 Sync eng/common directory with azure-sdk-tools for PR 5005
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/perf.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#1422 Added a backoff mechanism for the CommunicationTokenCredential for autorefresh feature
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
  sdk/communication/AzureCommunicationCommon/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshOnDemandTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshProactiveTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/CommunicationTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/StaticTokenCredentialTests.swift
Labels: Communication, Communication - Identity

#1437 Sync eng/common directory with azure-sdk-tools for PR 5027
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: EngSys, Central-EngSys

#1440 Sync eng/common directory with azure-sdk-tools for PR 5054
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1441 AzureCommunicationCalling 2.3.0-beta.4
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1442 Sync eng/common directory with azure-sdk-tools for PR 5059
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#1443 Sync eng/common directory with azure-sdk-tools for PR 5040
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#1445 Sync eng/common directory with azure-sdk-tools for PR 5095
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#1446 Sync eng/common directory with azure-sdk-tools for PR 5121
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
Labels: EngSys, Central-EngSys

#1447 Sync eng/common directory with azure-sdk-tools for PR 5113
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1448 Sync eng/common directory with azure-sdk-tools for PR 5134
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1449 [AzureCommunicationCommon]ObjC tests for CommunicationTokenCredential
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshOnDemandTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/AutoRefreshProactiveTokenCredentialTests.swift
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCAutoRefreshOnDemandTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCAutoRefreshProactiveTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCCommunicationTokenCredentialTests.h
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCCommunicationTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCStaticTokenCredentialTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjC/ObjCTokenParserTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
  sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
Labels: Communication

#1452 Remove CHECKENFORCER file
  eng/CHECKENFORCER
Labels: Central-EngSys

#1450 Sync eng/common directory with azure-sdk-tools for PR 5169
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1454 Sync eng/common directory with azure-sdk-tools for PR 5169
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1455 Sync eng/common directory with azure-sdk-tools for PR 5224
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1459 Sync eng/common directory with azure-sdk-tools for PR 5242
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#1458 Sync eng/common directory with azure-sdk-tools for PR 5231
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1462 Sync eng/common directory with azure-sdk-tools for PR 5272
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys
