Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-03, with the labels that each got.

#1484 Sync eng/common directory with azure-sdk-tools for PR 5581
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1485 Sync eng/common directory with azure-sdk-tools for PR 5540
  eng/common/scripts/Cadl-Project-Generate.ps1
Labels: EngSys, Central-EngSys

#1488 Sync eng/common directory with azure-sdk-tools for PR 5603
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#1487 Sync eng/common directory with azure-sdk-tools for PR 5595
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#1491 Sync eng/common directory with azure-sdk-tools for PR 5627
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1494 Sync eng/common directory with azure-sdk-tools for PR 5613
  eng/common/testproxy/override-proxy-version.ps1
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1496 Sync eng/common directory with azure-sdk-tools for PR 5702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1495 Sync eng/common directory with azure-sdk-tools for PR 5691
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#1499 Sync eng/common directory with azure-sdk-tools for PR 5742
  eng/common/scripts/trust-proxy-certificate.ps1
Labels: EngSys, Central-EngSys

#1504 [ChatSDK] Fixed issue when ChatSDK couldn't run for ARM64 simulator
  Podfile
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sdk/communication/AzureCommunicationChat/Package.swift
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj
  sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
Labels: Communication, Azure.Core, Azure.Identity

#1508 AzureCommunicationChat 1.3.1
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcworkspace/contents.xcworkspacedata
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  jazzy/AzureCommunicationChat.yml
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/CHANGELOG.md
  sdk/communication/AzureCommunicationChat/README.md
Labels: Communication

#1509 Sync eng/common directory with azure-sdk-tools for PR 5726
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1503 [Communication Identity] Update codeowners
  .github/CODEOWNERS
Labels: Communication, Communication - Common, Communication - Identity

#1490 Sync eng/common directory with azure-sdk-tools for PR 5608
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
  eng/common/scripts/get-codeowners.lib.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys
