Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-04, with the labels that each got.

#1512 Sync eng/common directory with azure-sdk-tools for PR 5918
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1513 Sync eng/common directory with azure-sdk-tools for PR 5924
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#1516 [ios] AzureCommunicationCommon 1.2.0-beta.1 release
  jazzy/AzureCommunicationCommon.yml
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
  sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCommon/CHANGELOG.md
Labels: Communication

#1518 Release iOS SDK AzureCommunicationCalling-2.3.0-beta.5
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1515 Sync eng/common directory with azure-sdk-tools for PR 5951
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#1520 Azure communication calling 2.3.0
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1521 Sync eng/common directory with azure-sdk-tools for PR 5991
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1522 Sync eng/common directory with azure-sdk-tools for PR 5995
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#1523 Sync eng/common directory with azure-sdk-tools for PR 6004
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#1524 Sync eng/common directory with azure-sdk-tools for PR 5911
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1525 Update from machine pools from Ubuntu 18.04 to Ubuntu 20.04
  eng/pipelines/templates/stages/archetype-ios-release.yml
Labels: Central-EngSys

#1528 Sync eng/common directory with azure-sdk-tools for PR 6045
  eng/common/scripts/Verify-RequiredDocsJsonMembers.ps1
Labels: EngSys, Central-EngSys

#1527 Enable event processor for iOS
  .github/event-processor.config
  .github/fabricbot.json
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys
