Repository Azure/azure-sdk-for-ios, pull requests merged in 2023-08, with the labels that each got.

#1588 Sync eng/common directory with azure-sdk-tools for PR 6611
  eng/common/testproxy/dotnet-devcert.crt
  eng/common/testproxy/dotnet-devcert.pfx
  eng/common/testproxy/onboarding/README.me
Labels: EngSys, Central-EngSys

#1589 Sync eng/common directory with azure-sdk-tools for PR 6670
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1590 Sync eng/common directory with azure-sdk-tools for PR 6739
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#1591 AzureCommunicationCalling 2.6.0
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1593 Azure Communication Calling iOS SDK 2.7.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1594 Sync eng/common directory with azure-sdk-tools for PR 6817
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1595 AzureCommunicationCalling 2.7.0-beta.2
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1592 Sync eng/common directory with azure-sdk-tools for PR 6782
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#1597 Sync eng/common directory with azure-sdk-tools for PR 6632
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1596 Sync eng/common directory with azure-sdk-tools for PR 6823
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1599 Sync eng/common directory with azure-sdk-tools for PR 6823
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1600 Sync eng/common directory with azure-sdk-tools for PR 6853
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: EngSys, Central-EngSys

#1605 Sync eng/common directory with azure-sdk-tools for PR 6867
  eng/common/pipelines/templates/steps/docsms-ensure-validation.yml
Labels: EngSys, Central-EngSys

#1606 Workaround SwiftFormat bug
  sdk/core/AzureCore/Source/DataStructures/AzureDate.swift
Labels: Azure.Core

#1607 Azure Communication Calling 2.6.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication
