Repository Azure/azure-sdk-for-ios, pull requests merged in 2024-01, with the labels that each got.

#1670 AzureCommunicationCalling_2.8.0-beta.3
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1671 Sync eng/common directory with azure-sdk-tools for PR 7468
  eng/common/scripts/Submit-PullRequest.ps1
Labels: EngSys, Central-EngSys

#1674 Sync eng/common directory with azure-sdk-tools for PR 7459
  eng/common/testproxy/scripts/tag-merge/README.md
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1675 Sync eng/common directory with azure-sdk-tools for PR 7498
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1676 Sync eng/common directory with azure-sdk-tools for PR 7445
  eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: EngSys, Central-EngSys

#1679 Sync eng/common directory with azure-sdk-tools for PR 7451
  eng/common/pipelines/templates/steps/verify-restapi-spec-location.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1681 [CODEOWNERS] Remove automation section
  .github/CODEOWNERS
Labels: EngSys, Client

#1682 Sync eng/common directory with azure-sdk-tools for PR 7536
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: EngSys, Central-EngSys

#1678 Sync eng/common directory with azure-sdk-tools for PR 7512
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#1673 Fix [BUG] https://github.com/Azure/azure-sdk-for-ios/issues/1672
  sdk/core/AzureCore/Source/Util/ApplicationUtil.swift
Labels: Azure.Core, Community Contribution, customer-reported

#1683 Sync eng/common directory with azure-sdk-tools for PR 7537
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
  eng/common/testproxy/onboarding/common-asset-functions.ps1
  eng/common/testproxy/scripts/resolve-asset-conflict/README.md
  eng/common/testproxy/scripts/resolve-asset-conflict/resolve-asset-conflict.ps1
  eng/common/testproxy/scripts/tag-merge/README.md
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1684 Sync eng/common directory with azure-sdk-tools for PR 7543
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1685 Sync eng/common directory with azure-sdk-tools for PR 7548
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1686 Sync eng/common directory with azure-sdk-tools for PR 7270
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#1687 Sync eng/common directory with azure-sdk-tools for PR 7556
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1677 AzureCommunicationCalling 2.8.0
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1689 Sync eng/common directory with azure-sdk-tools for PR 7580
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: EngSys, Central-EngSys

#1688 Sync eng/common directory with azure-sdk-tools for PR 7569
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1690 Sync eng/common directory with azure-sdk-tools for PR 7584
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1691 Sync eng/common directory with azure-sdk-tools for PR 7585
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys
