Repository Azure/azure-sdk-for-ios, pull requests merged in 2024-09, with the labels that each got.

#1866 Sync eng/common directory with azure-sdk-tools for PR 8912
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#1867 Sync eng/common directory with azure-sdk-tools for PR 8887
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#1868 Sync eng/common directory with azure-sdk-tools for PR 8928
  eng/common/spelling/package-lock.json
Labels: EngSys, Central-EngSys

#1872 Sync .github/workflows directory with azure-sdk-tools for PR 8942
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1871 Sync eng/common directory with azure-sdk-tools for PR 8929
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#1870 Sync eng/common directory with azure-sdk-tools for PR 8902
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#1869 Retrieve Trouter Config From ChatGW
  sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
  sdk/communication/AzureCommunicationChat/Source/Signaling/RealTimeNotificationConfiguration.swift
Labels: Communication

#1874 Sync eng/common directory with azure-sdk-tools for PR 8958
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1875 Sync eng/common directory with azure-sdk-tools for PR 8959
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#1876 Add auto-baseline main pipeline config for core
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Central-EngSys

#1877 Sync eng/common directory with azure-sdk-tools for PR 8963
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#1879 Sync eng/common directory with azure-sdk-tools for PR 8974
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#1880 Sync eng/common directory with azure-sdk-tools for PR 8994
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#1882 Sync .github/workflows directory with azure-sdk-tools for PR 8995
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1883 Sync eng/common directory with azure-sdk-tools for PR 9000
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1886 Sync eng/common directory with azure-sdk-tools for PR 9004
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#1884 Sync eng/common directory with azure-sdk-tools for PR 8998
  eng/common/pipelines/templates/steps/verify-readmes.yml
Labels: EngSys, Central-EngSys

#1887 Sync eng/common directory with azure-sdk-tools for PR 9008
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#1889 Azure Communication Calling 2.12.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#1888 Sync eng/common directory with azure-sdk-tools for PR 9016
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1892 Updating CODEOWNERS for 1espt config
  .github/CODEOWNERS
Labels: Central-EngSys

#1893 Update 1espt codeowners
  .github/CODEOWNERS
Labels: Central-EngSys

#1890 Sync eng/common directory with azure-sdk-tools for PR 9013
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#1896 Sync eng/common directory with azure-sdk-tools for PR 9035
  eng/common/scripts/Verify-ChangeLogs.ps1
Labels: EngSys, Central-EngSys

#1899 Sync eng/common directory with azure-sdk-tools for PR 9059
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#1898 Sync eng/common directory with azure-sdk-tools for PR 9057
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys
