Repository Azure/azure-sdk-for-ios, pull requests merged in 2025-04, with the labels that each got.

#2073 Sync eng/common directory with azure-sdk-tools for PR 10176
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#2076 Sync eng/common directory with azure-sdk-tools for PR 10191
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#2075 Sync eng/common directory with azure-sdk-tools for PR 10184
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2077 Sync eng/common directory with azure-sdk-tools for PR 10190
  eng/common/testproxy/test-proxy-standalone-tool.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2079 Sync eng/common directory with azure-sdk-tools for PR 10206
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2081 Sync eng/common directory with azure-sdk-tools for PR 10182
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#2074 AzureCore 1.0.0-beta.16
  examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
  examples/AzureSDKSmokeTest/Podfile
  jazzy/AzureCore.yml
  sdk/core/AzureCore/AzureCore.podspec.json
  sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
  sdk/core/AzureCore/CHANGELOG.md
  sdk/core/AzureCore/README.md
  sdk/core/AzureCore/Source/DataStructures/AzureDate.swift
  sdk/core/AzureCore/Source/DataStructures/CancellationToken.swift
  sdk/core/AzureCore/Source/DataStructures/Collections.swift
  sdk/core/AzureCore/Source/DataStructures/XMLMap.swift
  sdk/core/AzureCore/Source/DataStructures/XMLTree.swift
  sdk/core/AzureCore/Source/Pipeline/Pipeline.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineClient.swift
  sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift
  sdk/core/AzureCore/Source/Pipeline/Transport/RequestParameters.swift
  sdk/core/AzureCore/Source/Providers/BundleInfoProvider.swift
  sdk/core/AzureCore/Source/Providers/LocaleInfoProvider.swift
  sdk/core/AzureCore/Source/Providers/PlatformInfoProvider.swift
  sdk/core/AzureCore/Source/Util/ApplicationUtil.swift
  sdk/core/AzureCore/Source/Util/KeychainUtil.swift
  sdk/core/AzureCore/Source/Util/ReachabilityManager.swift
  sdk/core/AzureCore/Tests/CollectionsTests.swift
  sdk/core/AzureCore/Tests/Stubs/TestClient.swift
  sdk/core/AzureCore/Tests/XMLModelTests.swift
Labels: Azure.Core

#2082 Sync eng/common directory with azure-sdk-tools for PR 10238
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2084 Sync eng/common directory with azure-sdk-tools for PR 10246
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#2085 Azure Communication Calling 2.16.0-beta.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#2086 Sync eng/common directory with azure-sdk-tools for PR 10293
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#2087 Sync eng/common directory with azure-sdk-tools for PR 10314
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#2088 Sync eng/common directory with azure-sdk-tools for PR 10345
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2089 Sync eng/common directory with azure-sdk-tools for PR 10287
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#2090 Sync eng/common directory with azure-sdk-tools for PR 10400
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2091 Sync eng/common directory with azure-sdk-tools for PR 10377
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#2093 Sync eng/common directory with azure-sdk-tools for PR 10432
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: EngSys, Central-EngSys

#2094 Sync eng/common directory with azure-sdk-tools for PR 10411
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2095 Sync eng/common directory with azure-sdk-tools for PR 10461
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#2098 Sync eng/common directory with azure-sdk-tools for PR 10467
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#2099 Sync eng/common directory with azure-sdk-tools for PR 10491
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#2100 Sync eng/common directory with azure-sdk-tools for PR 10500
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#2102 Sync eng/common directory with azure-sdk-tools for PR 10482
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#2103 Sync eng/common directory with azure-sdk-tools for PR 10470
  eng/common/mcp/README.md
  eng/common/mcp/azure-sdk-mcp.ps1
  eng/common/scripts/Helpers/AzSdkTool-Helpers.ps1
  eng/common/testproxy/install-test-proxy.ps1
  eng/common/testproxy/test-proxy.ps1
Labels: EngSys, Central-EngSys

#2101 Sync .github/workflows directory with azure-sdk-tools for PR 10483
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#2104 Sync eng/common directory with azure-sdk-tools for PR 10508
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys
