Repository Azure/azure-sdk-for-ios, pull requests merged in 2025-03, with the labels that each got.

#2038 Sync eng/common directory with azure-sdk-tools for PR 9950
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2040 Sync eng/common directory with azure-sdk-tools for PR 9955
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2041 Sync eng/common directory with azure-sdk-tools for PR 9945
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2042 Sync eng/common directory with azure-sdk-tools for PR 9963
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2043 Sync eng/common directory with azure-sdk-tools for PR 9918
  eng/common/scripts/job-matrix/pullrequest-faq.md
Labels: EngSys, Central-EngSys

#2037 Sync eng/common directory with azure-sdk-tools for PR 9943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2045 Sync eng/common directory with azure-sdk-tools for PR 10013
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2047 Sync eng/common directory with azure-sdk-tools for PR 9993
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2049 Sync eng/common directory with azure-sdk-tools for PR 10030
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#2048 Sync eng/common directory with azure-sdk-tools for PR 10027
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2051 Resolve 1ES Release warning
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/stages/archetype-ios-release.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/AzureTemplate/CHANGELOG.md
  sdk/template/AzureTemplate/README.md
Labels: EngSys

#2052 Sync eng/common directory with azure-sdk-tools for PR 10039
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2053 Sync eng/common directory with azure-sdk-tools for PR 10041
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#2055 Sync eng/common directory with azure-sdk-tools for PR 10046
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2054 Sync eng/common directory with azure-sdk-tools for PR 10045
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2056 Sync .github/workflows directory with azure-sdk-tools for PR 10054
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#2057 Azure Communication Calling 2.15.1
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json
  sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
  sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Labels: Communication

#2058 Sync eng/common directory with azure-sdk-tools for PR 10081
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#2059 Repositories passed through to SDLStage
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  sdk/communication/ci.yml
  sdk/core/ci.yml
  sdk/template/AzureTemplate/AzureTemplate.podspec.json
  sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
  sdk/template/AzureTemplate/CHANGELOG.md
  sdk/template/AzureTemplate/README.md
  sdk/template/ci.yml
Labels: EngSys, Communication, Azure.Core

#2062 Sync eng/common directory with azure-sdk-tools for PR 10096
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2063 Sync eng/common directory with azure-sdk-tools for PR 10100
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#2064 Sync eng/common directory with azure-sdk-tools for PR 10129
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2061 Sync eng/common directory with azure-sdk-tools for PR 10099
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#2065 Sync eng/common directory with azure-sdk-tools for PR 10135
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#2068 Sync eng/common directory with azure-sdk-tools for PR 10004
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#2066 Sync eng/common directory with azure-sdk-tools for PR 10145
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2067 Sync eng/common directory with azure-sdk-tools for PR 10134
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
Labels: EngSys, Central-EngSys
